import os
import requests
import logging
from fastapi import FastAPI, BackgroundTasks
from pydantic import BaseModel
from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

# Configuration
PLANE_API_KEY = os.getenv("PLANE_API_KEY")
PLANE_URL = os.getenv("PLANE_URL", "http://localhost:8000").rstrip("/")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Event Planning Plane Agent")

# Initialize Gemini Client
try:
    genai_client = genai.Client(api_key=GEMINI_API_KEY)
except Exception as e:
    logger.warning(f"Failed to initialize Gemini Client. Check API Key. Error: {e}")
    genai_client = None

# We use a Pydantic schema for the LLM to guarantee structured JSON output
class Task(BaseModel):
    name: str
    description: str

class EventPlan(BaseModel):
    tasks: list[Task]

def generate_tasks_with_gemini(project_name: str, project_description: str) -> list[dict]:
    """Calls Gemini to generate a list of tasks for the event project."""
    if not genai_client:
        logger.error("Gemini client is not initialized.")
        return []

    prompt = f"""
    You are an expert event planner. A user has just created a new event project in our project management system.
    
    Event Name: {project_name}
    Event Description: {project_description}
    
    Based on the event details provided, generate a list of the 5 most critical tasks that need to be completed to make this event successful. 
    Ensure the tasks are actionable and specific to the type of event described.
    """
    
    try:
        logger.info(f"Asking Gemini to generate tasks for: {project_name}")
        response = genai_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=EventPlan,
            ),
        )
        
        # Pydantic schema guarantees it matches the EventPlan structure
        plan = EventPlan.model_validate_json(response.text)
        return [{"name": task.name, "description": task.description} for task in plan.tasks]
        
    except Exception as e:
        logger.error(f"Gemini API Error: {e}")
        return []

def create_plane_issue(workspace_slug: str, project_id: str, task_name: str, task_description: str):
    """Creates a new issue in Plane via the REST API."""
    url = f"{PLANE_URL}/api/v1/workspaces/{workspace_slug}/projects/{project_id}/issues/"
    headers = {
        "X-Api-Key": PLANE_API_KEY,
        "Content-Type": "application/json"
    }
    payload = {
        "name": task_name,
        "description_html": f"<p>{task_description}</p>"
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        logger.info(f"Successfully created issue: {task_name}")
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to create Plane issue '{task_name}': {e}")
        if hasattr(e, 'response') and e.response is not None:
            logger.error(f"Response body: {e.response.text}")

def process_project_creation(webhook_data: dict):
    """Background task to handle the project creation webhook."""
    try:
        project_id = webhook_data.get("id")
        project_name = webhook_data.get("name", "Unnamed Event")
        project_description = webhook_data.get("description", "")
        
        # Plane webhooks often include the workspace details nested in the payload
        # The exact structure depends on the webhook version, but usually it's under 'workspace'
        workspace = webhook_data.get("workspace", {})
        workspace_slug = workspace.get("slug")
        
        if not workspace_slug:
             logger.error("Could not find workspace slug in webhook payload. Cannot create issues.")
             return
             
        logger.info(f"Processing new project: {project_name} in workspace {workspace_slug}")
        
        # 1. Ask Gemini for Tasks
        tasks = generate_tasks_with_gemini(project_name, project_description)
        
        if not tasks:
            logger.warning("No tasks generated by Gemini. Falling back to default tasks.")
            tasks = [
                {"name": "Define event budget", "description": "Set a clear budget before booking anything."},
                {"name": "Book a venue", "description": "Secure a location for the event date."}
            ]
            
        # 2. Push Tasks back to Plane
        for task in tasks:
            create_plane_issue(
                workspace_slug=workspace_slug, 
                project_id=project_id, 
                task_name=task['name'], 
                task_description=task['description']
            )
            
    except Exception as e:
         logger.error(f"Error processing webhook: {e}")

@app.post("/plane-webhook")
async def plane_webhook(payload: dict, background_tasks: BackgroundTasks):
    """
    Endpoint to receive webhooks from Plane.
    """
    event_type = payload.get("event_type")
    
    # Plane webhook events: project.created, issue.created, issue_comment.created, etc.
    if event_type == "project.created":
        logger.info("Project created event received!")
        # Run the LLM and API calls in the background so we respond to the webhook quickly
        # Plane expects a 2xx response within a few seconds or it marks the webhook as failed
        background_tasks.add_task(process_project_creation, payload.get("data", {}))
        return {"status": "processing_project"}
        
    elif event_type == "issue_comment.created":
        logger.info("Issue comment received. Mentions could be processed here.")
        # TODO: Check if comment mentions the agent, then reply
        return {"status": "ignored"}
        
    else:
        logger.info(f"Ignored webhook event type: {event_type}")
        return {"status": "ignored"}

@app.get("/health")
async def health_check():
    return {"status": "healthy"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
